HTTP/1.0 503 Service Unavailable^M
Cache-Control: no-cache^M
Connection: close^M
Content-Type: text/html^M
^M
<html><body><h1>503 Ningun Servidor Esta Disponible para atender su solicitud</h1>
Revise su conexión.
</body></html>